spring:
  application:
    name: "booklog" # "booklog"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC ???? ??? ??
    url: jdbc:mysql://localhost:3306/booklog_private # jdbc:mysql://localhost:3306/{???????}
    username: root # MySQL ?? ??
    password: dkTldlqkf1! # MySQL ????

  jpa:
    database: mysql # ??? ?????? ?? ?? (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate?? ??? MySQL ??(dialect)
    show-sql: true # ??? SQL ??? ??? ???? ?? ??
    hibernate:
      ddl-auto: update # ?????? ?? ? ?????? ???? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? SQL ??? ?? ?? ???
kakao:
  book:
    rest-api-key: ${KAKAO_REST_API_KEY}