server:
  port: ${PORT:8080}

spring:
  application:
    name: "booklog" # "booklog"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{데이터베이스명}
    username: ${DB_USER} # MySQL 유저 이름
    password: ${DB_PW} # MySQL 비밀번호

  servlet:
    multipart:
      enabled: true
      maxFileSize: 200MB
      maxRequestSize: 300MB

  jpa:
    database: mysql # ??? ?????? ?? ?? (MySQL)
    # database-platform: org.hibernate.dialect.MySQLDialect # Hibernate?? ??? MySQL ??(dialect)
    show-sql: true # ??? SQL ??? ??? ???? ?? ??
    hibernate:
      ddl-auto: update # ?????? ?? ? ?????? ???? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? SQL ??? ?? ?? ???
        dialect: org.hibernate.dialect.MySQLDialect

kakao:
  book:
    rest-api-key: ${KAKAO_REST_API_KEY}

cloud:
  aws:
    s3:
      bucket: booklog-s3
      path:
        review : review
        profile : profile
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACTION_ACCESS_KEY_ID}
      secretKey: ${AWS_ACTION_SECRET_ACCESS_KEY}

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 7200000